apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=watermill/Dockerfile",
            "--context=git://github.com/devdavidkarlsson/kafka-k8s-demo.git#refs/heads/master",
            "--destination=foo-docker-registry:5000/watermill:latest",
            "--insecure"
            ]
  restartPolicy: Never
